config/routes.rb
Easy::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :stores
  resources :products
  root :to=>'stores#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_ability.rb
class ClientAbility < ActiveRecord::Base
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.has_role? :admin
      can :manage, :all if user.role == "admin"
    end
  end
end

app/models/admin_page.rb
class AdminPage < ActiveRecord::Base

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/client_ability.rb
class ClientAbility < ActiveRecord::Base
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role?(:client)
      can :manage, Store, :user_id => user.id
      can :manage, Product, :user_id => user.id
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :store
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "135x135>" }, :default_url => "/assets/:style/missing.png"
  def user
    self.store.user
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :products
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :store
  has_many :products, :through=>:store

  ROLES = %w(client admin end_user)

  # Privileges are inherited between roles in the order specified in the ROLES
  # array. E.g. A moderator can do the same as an editor + more.
  #
  # This method understands that and will therefore return true for moderator
  # users even if you call `role?('editor')`.
  def role?(base_role)
    return false unless role # A user have a role attribute. If not set, the user does not have any roles.
    ROLES.index(base_role.to_s) <= ROLES.index(role)
  end


  after_create :init_store
  #
  def init_store
    self.create_store(:name=>"Example Store", url: 'example.com', description:"No description yet. Check back soon!")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end


end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  respond_to :js,:html,:json
  protect_from_forgery :except => [:edit,:new]

  include ActionView::Helpers::TextHelper

  def show
    @product=Product.find(params[:id])
    render
  end
  def edit
    @product=Product.find(params[:id])
    @modal=OpenStruct.new({:title=>"Edit"})

  end

  def new
    @product=Product.new
    @modal=OpenStruct.new({:title=>"New Product"})

    render 'edit', :format=>:js
  end

  def update
    @product=Product.find(params[:id])
    @product.update_attributes!(product_params)
    redirect_to :back
  end
  def index
    redirect_to store_index_path
  end


  private
  def product_params
    params.require(:product).permit(:title, :description,:price,:count,:image)
  end
end

app/controllers/stores_controller.rb
class StoresController < InheritedResources::Base
  protect_from_forgery :except => [:edit]
  def index
    @stores=Store.all
    render
  end
  def show
    @store=params[:id].nil? ? current_user.store : Store.find(params[:id])
    @products=@store.products
    @container='hide'
    render
  end
  def edit
    @store=params[:id].nil? ? current_user.store : Store.find(params[:id])
    @modal=OpenStruct.new({:title=>'Edit'})
    render
  end

  def update
    @store=Store.find(params[:id])
    @store.update_attributes!(store_params)
    redirect_to stores_path
  end

  private
  def store_params
    params.require(:store).permit(:name, :description,:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def host
    return 'http://192.168.1.201:4000'
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script>
      window.absolute='<%="#{request.protocol}#{request.host_with_port}"%>';
  </script>
  <title>Easy</title>
  <%= stylesheet_link_tag    "application",'//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0-rc2/css/bootstrap.min.css', media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag(
              '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0/js/bootstrap.min.js','stores'
 ) %>
</head>
<body>
<%= javascript_include_tag   "//cdnjs.cloudflare.com/ajax/libs/holder/2.0/holder.js" %>

<%if @container!='hide'  %>
    <div class='container'>
      <div id='page-content'>
        <%= yield %>
      </div>
    </div>
<%else  %>
    <%=yield%>
<%end  %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true } ) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
    <%= f.file_field :image%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/edit.js.erb
bootbox.dialog({
    message: "<%=j render 'form' %>",
    title: "<%= @modal.title %>",
});

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class='container'>
  <div class="col-md-4">
    <%= image_tag @product.image.url(:medium) %>
    <br />
    <p></p><i> $ <%= @product.price||="N/A" %>    </i>
    <span class='badge badge-important'>  <%= @product.count ||=0%> </span>   </p>
  </div>
  <div class="col-md-8">
    <h3>  <%= @product.title %>    </h3>
    <p>  <%= @product.description %>    </p>
  </div>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', :back  %>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/_show.html.erb
<div class="modal fade container-fluid" id="swagModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="width:100%">
    <div class="modal-content ">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><%= @store.name %></h4>
      </div>
      <div class="modal-body">

        <ul style='list-style: none' class='media'>
          <%@store.products.each do |product|%>
              <li class='panel col-md-3  container' title='<%= product.title %>'>
                <div class="col-mid-6 pull-left">
                  <%=link_to(products_path(product.id)) do%><img class="media-object" data-src="holder.js/135x135" /><%end%>

                  <h6 class="media-title"><%=product.title %></h6>
                  <p class="media-caption">$<%=product.price||='N/A' %></p>

                  <%= javascript_include_tag("//cdnjs.cloudflare.com/ajax/libs/holder/2.0/holder.js") %>
                </div>
                <div class="col-mid-6">

                  <%= truncate(product.description,:omission => "... (continued)", :length => 75) %>
                </div>
                <span><%=content_tag(:a,"#",:onclick=>"get_product_edit(#{product.id},'edit-product-modal')",:remote=>true,:method=>:get) do%>"EDIT"<%end%></span>
              </li>
          <%end%>
          <li class='panel col-md-3  container'>
            <span><%=button_to(new_product_path(:callback=>"new-product-modal",:format=>"js"),:remote=>true,:method=>:get,:class=>'btn btn-large btn-light') do%>
                  <i class='icon-plus icon-large white'/>
                Add New Product
                  <%end %>
              </span>
          </li>
        </ul>
      </div>
      <hr class='hr dotted'/>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
 <script>

     function get_product_edit(pid, callback){
         $.ajax({url: "<%= root_url %>/products/"+pid+"/edit",complete:function(data){$('#'+callback).html(data)}})
     };
 </script>
<div id="new-product-modal"></div>
<div id="edit-product-modal"></div>

app/views/stores/edit.js.erb
bootbox.dialog({
    message: "<%=j render 'form' %>",
    title: "<%= @modal.title %>",
});

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%=link_to(store.user.email, '#') %></td>
        <td><%= store.name %></td>
        <td><%= store.description %></td>
        <td><%= store.url %></td>
        <td><%= button_to 'Edit', edit_store_path(store),:remote=>true,:format=>:js,:method=>:get %></td>
        <td id='store-nav-<%= store.id %>'></td>
      </tr>
      <script>
        $(document).ready(function(){
          append_frame('<%=store.id%>','store-nav-<%= store.id %>');
          //easy_store('<%#=store.id%>','<%#= store.name %>','store-nav-<%#= store.id %>');
      }) ;
      </script>

  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

<pre>To add easy_store:
<%="to include provided JS"%>
init_swag();
  For JS - no-iframe
<%="<script>easy_store(store #, display name, placement div)</script>"%>

  For iframe
  <%="<script>append_frame(store #, placement div)</script>"%>

</pre>

app/views/stores/show.html.erb
<ul style='list-style: none' class='media' id='media-grid'>
  <%@store.products.each do |product|%>
      <li class='panel col-md-3  container' title='<%= product.title %>'>
        <div class="col-lg-4 pull-left">
          <%=link_to(image_tag(product.image.url(:thumb), :class=>'media-object'), product_path(product.id),:style=>"width: 135px;height: 135px;display: block;")%>

          <%= javascript_include_tag("//cdnjs.cloudflare.com/ajax/libs/holder/2.0/holder.js") %>
        </div>
        <div class="col-lg-8">
          <%=link_to(product_path(product.id)) do%>
          <h4 class="media-title"><%=truncate(product.title,:length=>15,:omission=>'...') %></h4>
          <%end%>
          <h5 class="media-caption strong">$<%=product.price||='N/A' %>
            <%= content_tag(:span, :class=>'badge') do%>
                <%=product.count||="none"%> in stock
            <%end%>
          </h5>
          <%=raw( truncate(product.description,:omission => raw("...\n (continued)"), :length => 175)) %>
        </div>

        <span><%=button_to("EDIT",edit_product_path(:id=>product.id,:callback=>"edit-product-modal",:format=>"js"),:remote=>true,:method=>:get,:form_class=>'container',:class=>'col-lg-12')%></span>
      </li>
  <%end%>
  <li class='panel col-md-3  container'>
    <span><%=button_to(new_product_path(:callback=>"new-product-modal",:format=>"js"),:remote=>true,:method=>:get,:class=>'btn btn-large btn-light ') do%>
          <i class='icon-plus icon-large white'/>
        Add New Product
          <%end %>
      </span>
  </li>
</ul>
<script>
    get_height_largest_child($('#media-grid'));
</script>

app/views/stores/show.js.erb
var root=$('<%=j render :partial=>"show" %>');
$('body').append(root);
$('#swagModal').modal('show');